name: CI pi pipeline

on:
  workflow_dispatch: # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add Pi to known_hosts
        run: |
          ssh-keyscan -H shakepi >> ~/.ssh/known_hosts

      - name: Create README File
        run: |
          ssh shake@shakepi "
            cd ~/Desktop/CI-testing
            touch README.md
          "

      # - name: Copy entire repository to Raspberry Pi
      #   run: |
      #     scp -r -o ConnectTimeout=30 ./* ${{ secrets.RASPBERRY_PI_USERNAME }}@${{ secrets.RASPBERRY_PI_IP }}:/home/${{ secrets.RASPBERRY_PI_USERNAME }}/Desktop/CI-testing
