name: CI pi pipeline

on:
  workflow_dispatch: # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: 1.76.0

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH directory
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Add Pi to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.TS_PI_IP }} >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      - name: Copy files to Raspberry Pi
        run: |
          ssh ${{ secrets.PI_USERNAME }}@${{ secrets.TS_PI_IP }} "
            mkdir -p ~/Desktop/project/build"
          scp -r ./* ${{ secrets.PI_USERNAME }}@${{ secrets.TS_PI_IP }}:~/Desktop/project

      - name: Compile and Upload Code to Teensy
        run: |
          ssh ${{ secrets.PI_USERNAME }}@${{ secrets.TS_PI_IP }} "
            export PATH=\$HOME/bin:\$PATH
            echo 'Starting compilation...'
            ( 
              arduino-cli compile --fqbn teensy:avr:teensy41 --output-dir ~/Desktop/project/build ~/Desktop/project/project.ino && 
              echo 'Compilation successful, uploading...' &&
              cd ~/bin &&
              sudo ./teensy_loader_cli -w -v -s -mmcu=TEENSY41 ~/Desktop/project/build/project.ino.hex
            ) || { echo 'Compilation or upload failed'; exit 1; }
          "
